<?php

namespace ContainerFxSVqkF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3G2gVemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3G2gVem' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3G2gVem'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'achatRepository' => ['privates', 'App\\Repository\\AchatRepository', 'getAchatRepositoryService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'achatRepository' => 'App\\Repository\\AchatRepository',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
